### ISSUE TITLE
uninstall openebs after every test case

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/d-operators#32]
- In our test cases we are installing openEBS and after installing openEBS we need to uninstall it.
- Uninstallation of openebs includes multiple tasks and after that also few times it gets stuck in terminating state.

**Comment by AmitKumarDas** [comment]
we may want to make this example more reliable & put it to use:
https://github.com/AmitKumarDas/metac/tree/master/examples/gctl/uninstall-openebs

@amitbhatt818 can you provide more details on why is this getting stuck in terminating state & so on. More details will help us design better.
